var src = "\n  <div id=\"img\"><img src=\"\"/></div>\n  <span id=\"id\"><span id=\"tab\"></span></span>\n  <span id=\"at\"><b>@</b><a href=\"\"></a><small><small></span>\n";
var post = "\n  <div id=\"post\"><p></p></div>\n";
var media = "\n  <div id=\"media\"></div>\n";
var engage = "\n  <div id=\"engage\">\n    <div id=\"e1\"></div>\n    <div id=\"e2\"></div>\n    <div id=\"e3\"></div>\n    <div id=\"e4\"></div>\n  </div>\n";
var canvas = "\n  " + src + "\n  " + post + "\n  " + media + "\n  " + engage + "\n";
var newsfeed = "\n<div id=\"newsfeed\">\n  " + canvas + "\n</div>\n";
var liveview = "\n<div id=\"liveview\"></div>\n";
var drops = "\n<div id=\"drops\"></div>\n";
var journal = "\n<div id=\"journal\"></div>\n";
var messages = "\n<div id=\"messages\"></div>\n";
var circles = "\n<div id=\"circles\"></div>\n";
var passport = "\n<div id=\"passport\"></div>\n";
var settings = "\n<div id=\"settngs\"></div>\n";
var synergy = "\n<div id=\"synergy\"></div>\n";
var c1 = "\n  <div id=\"c1\">" + newsfeed + "</div>\n";
var c2 = "\n  <div id=\"c2\">" + liveview + "</div>\n";
var c3 = "\n  <div id=\"c3\">" + drops + "</div>\n";
var c4 = "\n  <div id=\"c4\">" + journal + "</div>\n";
var c5 = "\n  <div id=\"c5\">" + messages + "</div>\n";
var c6 = "\n  <div id=\"c6\">" + circles + "</div>\n";
var c7 = "\n  <div id=\"c4\">" + passport + "</div>\n";
var c8 = "\n  <div id=\"c5\">" + settings + "</div>\n";
var c9 = "\n  <div id=\"c6\">" + synergy + "</div>\n";
var expo = "\n  <div id=\"expo\">\n    " + c1 + "\n    " + c2 + "\n    " + c3 + "\n  </div>\n";
document.body.innerHTML = expo;
